# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6588b5965206804ef0c5cf60225025138dd1ad7e7d309acf2e52b9aa952eb6302e122c5293374e83fbf669ead57d56e2d56f5f91fa28c81ab0ae9dd3f5b5f2e

test:
  secret_key_base: 0202e9d9167cfa9e22367ae76212592047e270dbf6eebb480fd66a8e0124cd6dcff2e7e73dbdc2b7302efd19eeccb9d40e681251f29eb22fd376a1a5e8b97de3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
